sudo: false
language: rust
rust:
- stable
- beta
env:
  global:
  - RUST_BACKTRACE=1
  - PKGNAME=twig
  - LOCAL="~/.local"
  - secure: "n4u/OAY9X6HtfgHP0rUQbBK+cY7tBj8dwEwduDBbZShsUY2LTo6xP7bypjP5ee13LlIAwZHXk1IusWYvVzwYmygPNtR+9SDbKvJDWpuHuvczyqWGRGIsYBLtveZr0i6Px48fJQ4lr7MbZMyTBaLhSzYI5CGo8ZmBU56NGYpAw0oXf2cgBRhbSNyPrFBzaeFluWbpD8UYDNVziMmmiSyivT7WZa+/e/QL66KplhUWxM/ed7cp8jrOsfOjG5H2/8+W4G2AVKmsyhuXBSanEeHo+ewVxxhSZDVfyeXh0LYMROGP5MFl2wtWrOOFYBIRQAa1F5vnC4sV/AaMeAe01cBtiCmgdLym2AGgh6E+jiZdUEPUBJ4rLUvEhb2gOEAlK0xjr10jJOLbsE5yfSnt94OQJyHZcDjj2a29rX5PJ0YLPzZ/FEBgQ16uCniCABNb+Koq/T+IBixrUxwvZ+KDCCcDv1ZC18SEd18jEqOqmBil/HA6AnUpndyZPPlvq5lEhlo/ZwdJTGOSOsRcrBwUEIqTi7m/PDRfgbdD2a/7zTbHWN3y7sD6wFw7iTCbjDMQQLJzwONUzUxbBP62OmWfj4NtKs3GwTAfOG/unn7YJmwsnaImuv3aHC7Bnbd5DzXlflZK5aTAK+W2JwTjZQludJjfJK8jGk4ekv1OqfIJokZE5bc="
before_script: |
  pip install 'travis-cargo<0.2' --user # https://github.com/huonw/travis-cargo
  export PATH=$LOCAL/bin:$PATH
script: |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo bench &&
  travis-cargo doc
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - libbfd-dev
after_success: |
  # `travis-cargo --only stable doc-upload` didn't work for me ...
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=`echo $PKGNAME | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  pip install ghp-import --user &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages > /dev/null 2>&1

  # `travis-cargo coveralls` didn't work for me - so do it manually
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build &&
  cmake -DCMAKE_INSTALL_PREFIX:PATH=$LOCAL .. && make &&
  make install && cd ../.. &&

  kcov --verify \
       --coveralls-id=$TRAVIS_JOB_ID \
       --exclude-pattern=/.cargo \
       target/kcov target/debug/$PKGNAME-*
