(function() {var implementors = {};
implementors['regex_syntax'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='regex_syntax/struct.Error.html' title='regex_syntax::Error'>Error</a>",];implementors['regex'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='regex/enum.Error.html' title='regex::Error'>Error</a>",];implementors['twig'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='twig/engine/error/enum.TwigError.html' title='twig::engine::error::TwigError'>TwigError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='twig/engine/error/enum.ExtensionRegistryError.html' title='twig::engine::error::ExtensionRegistryError'>ExtensionRegistryError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='twig/engine/parser/error/enum.ParserError.html' title='twig::engine::parser::error::ParserError'>ParserError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='twig/engine/parser/error/enum.NodeError.html' title='twig::engine::parser::error::NodeError'>NodeError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='twig/engine/parser/token/error/enum.TokenError.html' title='twig::engine::parser::token::error::TokenError'>TokenError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='twig/engine/parser/lexer/error/enum.SyntaxError.html' title='twig::engine::parser::lexer::error::SyntaxError'>SyntaxError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='twig/engine/parser/lexer/error/enum.LexerError.html' title='twig::engine::parser::lexer::error::LexerError'>LexerError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='twig/runtime/error/enum.RuntimeError.html' title='twig::runtime::error::RuntimeError'>RuntimeError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='twig/loader/error/enum.LoaderError.html' title='twig::loader::error::LoaderError'>LoaderError</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
